trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.x'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: UseDotNet@2
  displayName: 'Install .NET $(dotnetVersion) SDK'
  inputs:
    version: '$(dotnetVersion)'

- script: |
    chmod +x ./bump-version.sh
    VERSION=$(cat version | ./bump-version.sh)
    echo "$VERSION" > version
    git config --global user.email "azure-pipeline@szogun-ui.pl"
    git config --global user.name "Azure pipeline"
    git add version
    git commit -m "[skip ci]"
    git push
    git tag "releases/$VERSION"
    git push origin "releases/$VERSION"
    echo "##vso[task.setvariable variable=packageVersion]${VERSION}-alpha"
    echo "##vso[task.setvariable variable=assemblyVersion]${VERSION}.0"
  displayName: 'Bump version'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'src/MediatR.AspNetCoreMvc.Helpers.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'src/MediatR.AspNetCoreMvc.Helpers.sln'
    arguments: >-
      --configuration $(buildConfiguration)
      --no-restore
      -p:GeneratePackageOnBuild=false
      -p:Version=$(packageVersion)
      -p:AssemblyVersion=$(assemblyVersion)
      -p:FileVersion=$(assemblyVersion)

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: 'src/MediatR.AspNetCoreMvc.Helpers/MediatR.AspNetCoreMvc.Helpers.csproj'
    nobuild: true
    versioningScheme: 'off'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    arguments: '--no-build -p:PackageVersion=$(packageVersion)'

- task: PublishPipelineArtifact@1
  displayName: 'Publish artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'nupkg'

- task: DotNetCoreCLI@2
  displayName: 'Push to NuGet.org'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'
